title: Introduction to Digital Humanities portfolio | Sophie Gala
description: Welcome to my site reflecting on Introduction to Digital Humanities
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
